### ISSUE TITLE
Add updated FRD and requirement to release mapping

### ISSUE THREAD

**Issue by tanush-r** [OpenTechXLabs/SmartHRM#27]
# Add AI assistant

## Feature
Name: Documentation

## Tasks
- [x]  Add user personas
- [x]  Add requirements with requirement ID
- [x]  Add Diagrams
- [x]  Add requirement to release mapping
- [x]  Update main README with new document links

## Description
Modifying the FRD for better user readability and easier contribution

## Status
- [x]  In-progress
- [x]  Reviewed
- [x]  Completed
