### ISSUE TITLE
Add Material design to masters

### ISSUE THREAD

**Issue by kruthvik19** [OpenTechXLabs/SmartHRM#32]
# Add Material design to masters

## Feature
Name: Masters 
Number: 7,8,9

## Tasks
- [x]  add material Ui for Candidate master 
- [x]  add material Ui for Client master 
- [x] add material Ui for Requirement master 

## Status
- [x]  In-progress
- [x]  Reviewed
- [x]  Completed
