### ISSUE TITLE
implement login authentication system

### ISSUE THREAD

**Issue by bhoomikasarapure** [OpenTechXLabs/SmartHRM#37]
# Add AI assistant

## Feature
Name: Authentication
Number: 6

## User Story
As a HR user,  I want to securely log in to the system and get high-level updates on client and requirement details, so I can measure the HR team's productivity. This way, only authorized users can access sensitive data.

## Tasks
- [ ]  Task 1: set up firebase authentication in angular.
- [ ]  Task 2: create a login page with email and passsword field.
- [ ] Task 3: create a service in angular to handle login and logout using firebase

## Description
Create a login system in Angular that uses Firebase for authentication. Users will log in using their email and password, and if successful, they will be redirected to the dashboard where they can access client and requirement updates. Only logged-in users should be able to access the dashboard, using Firebase for secure authentication.

## Status
- [ ]  In-progress
- [ ]  Reviewed
- [ ]  Completed
